#wps密码配置
docs-center-platform:
  url: http://192.168.30.185/open
  app-id: AK20211220KKTDLW
  app-key: 04867f0f4d2572a40b1f2d879d64e441
  scope: file_preview,file_edit,file_format_control

# MinIo文件服务器
minio:
  endpoint: http://192.168.30.127:9000
  #  映射到外网/政务网服务地址
  net-endpoint: http://117.173.87.121:9000
  # http://yy.ngrok2.xiaomiqiu.cn
#  accessKey: AKIAIOSFODNN7EXAMPLE
#  secretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: wps

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.30.127:5432/wps
    username: postgres
    password: scyj123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 50MB  #单个数据大小
      max-request-size: 100MB #总数据大小